# Laboratorio Forward Propagation
**José Barrios - 20007192**

## Instrucciones
Implementar forward-propagation para los 3 diagramas dados, en el tercer diagrama analizar la representación intermedia (ver descripción detallada en diapositiva 8).

## Definición de función de propagación 
Contrsuiremos una función que reciba las matrices de pesos entre capas. Para esto se necesita tener una estructura de datos (lista) que tenga en memoria todas estas matrices de pesos sinápticos.

Cada una de las matrices de pesos necesita estar construida de tal manera que la cantidad de filas represente la cantidad de variables de una obseración X (las columnas de X), y que la cantidad de columnas de la matriz sea la cantidad de neuronas de la siguiente capa.

In [1]:
import numpy as np

In [2]:
#Función de activación 
def sigmoid(X):
  return 1/(1 + np.exp(-X))

In [3]:
class RedNeuronal:
  def __init__(self, W):
    self.W = W

  def forward_propagation(self, X):
    #X como entrada de la primera capa oculta
    #A será representará la entrada de las siguientes capas y luego la salida final
    A = X
    
    #Ciclo para calcular los valores de cada capa
    for pesos in self.W:
        z = np.matmul(A, pesos)
        A = sigmoid(z)

    return A

### Diagrama 1

<img src='diagrama1.png'>

In [7]:
#Pesos de las entradas hacia la capa oculta 1
W_I_H1 = np.array([[0.8, 0.4, 0.3],
                   [0.2, 0.9, 0.5]])

#Pesos de la capa oculta 1 hacia la salida
W_H1_O = np.array([[0.3], 
                   [0.5], 
                   [0.9]])

#Lista de pesos entre capas
W = [W_I_H1, W_H1_O]

In [8]:
input_diagrama1 = np.array([1, 1]) #Para determinar que sea la misma salida de la imagen (0.77)

In [9]:
red_diagrama1 = RedNeuronal(W)

In [10]:
red_diagrama1.forward_propagation(input_diagrama1)

array([0.77438027])

Obtenemos la misma salida de la imagen, así que podemos probar con entradas con mayor cantidad de observaciones.

In [14]:
input_diagrama1 = np.array([[1, 1], 
                           [0, 0], 
                           [0, 1], 
                           [1, 0], 
                           [0.5, 0.5], 
                           [0.75, 0.25], 
                            [0.1, 0.2]])

In [15]:
red_diagrama1.forward_propagation(input_diagrama1)

array([[0.77438027],
       [0.70056714],
       [0.74661477],
       [0.7356216 ],
       [0.74155414],
       [0.73869891],
       [0.71414222]])

### Diagrama 2

<img src='diagrama2.png'>

In [16]:
#Pesos de las entradas hacia la capa oculta 1
W_I_H1 = np.array([[0.9, 0.3, 0.2],
                   [0.8, 0.5, 0.4], 
                   [0.1, 0.6, 0.7]])

#Pesos de la capa oculta 1 hacia la salida
W_H1_O = np.array([[0.3], 
                   [0.5], 
                   [0.9]])

#Lista de pesos entre capas
W = [W_I_H1, W_H1_O]

In [20]:
input_diagrama2 = np.array([1, 0, 1]) #Para determinar que sea la misma salida de la imagen (0.77)

In [18]:
red_diagrama2 = RedNeuronal(W)

In [21]:
red_diagrama2.forward_propagation(input_diagrama2)

array([0.77112013])

In [22]:
input_diagrama2 = np.array([[0.5, 0.5, 0.5], 
                            [0.2, 1, 0], 
                            [-1, 0, 1], 
                            [-0.2, -0.5, 0], 
                            [0.1, 0.2, 0.5], 
                            [0.4, 0.2, 0.1]])

In [23]:
red_diagrama2.forward_propagation(input_diagrama2)

array([[0.7574387 ],
       [0.74721089],
       [0.71918899],
       [0.67161418],
       [0.73591525],
       [0.72614304]])

### Diagrama 3

<img src='diagrama3.png'>

In [24]:
#Pesos de las entradas hacia la capa oculta 1
W_I_H1 = np.array([[0.3, 0.22, 0.65],
                   [0.46, -0.7, 0.9], 
                   [0.02, 0.65, 0.34]])

#Pesos de la capa oculta 1 hacia la capa oculta 2
W_H1_H2 = np.array([[-0.3, 0.45, 0.65],
                   [0.62, 0.57, 0.58], 
                   [0.45, 0.48, -0.45]])

#Pesos de la capa oculta 1 hacia la salida
W_H2_O = np.array([[-0.23, 0.9], 
                   [0.22, 0.88], 
                   [0.77, -0.4]])

#Lista de pesos entre capas
W = [W_I_H1, W_H1_H2, W_H2_O]

In [25]:
red_diagrama3 = RedNeuronal(W)

In [26]:
input_diagrama3 = np.array([1, 0, 1])
red_diagrama3.forward_propagation(input_diagrama3)

array([0.61889026, 0.7270697 ])

In [28]:
input_diagrama3 = np.array([[0, 0.5, 1], 
                           [-1, -0.5, 1], 
                           [0.1, 0.3, 2], 
                           [0, 1, 3], 
                           [3, 0, 1], 
                           [0.1, 0.1, 0.1]])
red_diagrama3.forward_propagation(input_diagrama3)

array([[0.61605707, 0.72085441],
       [0.6191183 , 0.70940566],
       [0.618896  , 0.72913813],
       [0.61939623, 0.73501733],
       [0.62203047, 0.73593835],
       [0.61566286, 0.71211039]])

## Conclusión
Es necesario tener presente la dimensionaldiad de las matrices para que no surjan errores de dimensionalidad no compatible. Realizar primero las operaciones a mano es un buen ejercicio para captar la idea de forward propagation.